[[main]]
  identifier = "posts"
  name = "Posts"
  url = "posts"
  weight = 1

[[main]]
  identifier = "guides"
  name = "Guides"
  url = "guides"
  weight = 2

[[main]]
  identifier = "cheatsheets"
  name = "Cheatsheets"
  url = "cheatsheets"
  weight = 3

[[main]]
  identifier = "science"
  name = "Science"
  url = "science"
  weight = 4

[[main]]
  identifier = "archive"
  name = "Archive"
  url = "archive"
  weight = 5

[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 6
